### PR TITLE
Update python/huaweimirror

### PR DESCRIPTION
**Pull request by b3nguang**

### CODE REVIEW

**Comment by bytemain** [comment]
@aooohan there is already a `python/npmmirror` ,should we have many `china mirrors`?

a better way is make `python/npmmirror` support config mirror url.

**Comment by aooohan** [comment]
> @aooohan there is already a `python/npmmirror` ,should we have many `china mirrors`?

Of course not. ;)
> 
> a better way is make `python/npmmirror` support config mirror url.

Yes.

There are no plans to merge any new PRs until the 0.3.0 refactoring is complete.

I'm currently having a good idea, such as allowing the plugin to be preconfigured with some MIRRORs (or other configurations, feel free to imagine), which can be toggled via `vfox switch` command, such as `vfox switch python npmmirror` or `vfox switch python huawei`, after that it will be permanent, and the plugin will be able to use the user-specified configuration. It's a preliminary idea, of course.

**Comment by aooohan** [comment]
@b3nguang Thanks for the contribution! Please wait patiently for the arrival of 0.3.0, and then you can contribute this change to the new python plug-in repository!

**Comment by bytemain** [comment]
Done by https://github.com/version-fox/vfox-python/pull/3

Now you can use `VFOX_PYTHON_MIRROR` to change mirror:

```sh
export VFOX_PYTHON_MIRROR=https://mirrors.huaweicloud.com/python/
```

**Pull request closed without merging**
