### PR TITLE
feat: support Erlang/OTP & Elixir

### PR DESCRIPTION
**Pull request by yeshan333**
## Testing

- [x] MacOS Darwin
- [x] Linux Ubuntu 20.04 LTS

### MacOS (Passed)

erlang macos testing

### Linux (Passed)

erlang linux testing

### MacOS (Passed)

elixir macos testing

### Linux (Passed)

elixir linux testing

### CODE REVIEW

**Comment by aooohan** [comment]
@yeshan333 Thanks for the contribution! Please wait patiently for the arrival of 0.3.0, and then you can maintain this plugin on your own repo or new repo on version-fox org, which depends on your wishes.

**Comment by yeshan333** [comment]
> @yeshan333 Thanks for the contribution! Please wait patiently for the arrival of 0.3.0, and then you can maintain this plugin on your own repo or new repo on version-fox org, which depends on your wishes.



> @yeshan333 Thanks for the contribution! Please wait patiently for the arrival of 0.3.0, and then you can maintain this plugin on your own repo or new repo on version-fox org, which depends on your wishes.

Where can we see some plans or overall  roadmap for vfox?

**Comment by yeshan333** [comment]
> @yeshan333 Thanks for the contribution! Please wait patiently for the arrival of 0.3.0, and then you can maintain this plugin on your own repo or new repo on version-fox org, which depends on your wishes.

Where can we see some plans or overall roadmap for vfox?

**Comment by aooohan** [comment]
> Where can we see some plans or overall roadmap for vfox?

Currently, there is no place to see it, as of now, and roughly the plan is
 1. Refactoring of the plugin system version-fox/vfox#112
 2. Compatible with legacy profiles, such as `.nvmrc` `.node-version` etc.

**Comment by aooohan** [comment]
@yeshan333 Hi, Can use reimplement this by new template?  Refer: 
https://vfox.lhan.me/zh-hans/plugins/create/howto.html

**Comment by yeshan333** [comment]
> @yeshan333 Hi, Can use reimplement this by new template? Refer: https://vfox.lhan.me/zh-hans/plugins/create/howto.html

Okay, Let me take a look.

Can I direct create plugin repo in [version-fox](https://github.com/version-fox) org? @aooohan

**Comment by aooohan** [comment]
> Can I direct create plugin repo in [version-fox](https://github.com/version-fox) org? @aooohan

I see you've already created it, you can transfer it to VersionFox org when you're done, and then I'll set you up as the administrator of the repository.

**Comment by yeshan333** [comment]
> > Can I direct create plugin repo in [version-fox](https://github.com/version-fox) org? @aooohan
> 
> I see you've already created it, you can transfer it to VersionFox org when you're done, and then I'll set you up as the administrator of the repository.

Hi, I have already implemented the plugin. Can you invite me to join the  [version-fox](https://github.com/version-fox) organization? @aooohan 

- https://github.com/yeshan333/vfox-elixir
- https://github.com/yeshan333/vfox-erlang

**Comment by aooohan** [comment]
@yeshan333  I have invited you, please check your email.

**Pull request closed without merging**
